### ISSUE TITLE
Settings don't persist after restart

### ISSUE THREAD

**Issue by ebremer** [suchorski/springboot-keycloak-server#5]
I'm trying out your latest build.  It starts up fine and appears to operate fine.  However, when I activated "Direct access grants" and added another valid redirect, they saved and appeared to work, but after I restarted the program, the two settings changed, reverted back to the default

**Comment by suchorski** [comment]
> I'm trying out your latest build.  It starts up fine and appears to operate fine.  However, when I activated "Direct access grants" and added another valid redirect, they saved and appeared to work, but after I restarted the program, the two settings changed, reverted back to the default

Hi, thanks for your message.

Are you using the default configuration? If yes, it uses H2 Memory Database. If you want to persist the data, you need to provide another database like MySQL or Postgres, or even change the H2 to store the database on a file instead of memory.

**Comment by ebremer** [comment]
My application.yml file looks like this but still doesn't persist:
```
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    username: sa
    password:
    url: jdbc:h2:file:./data/keycloak;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
        
keycloak:
  server:
    context-path: /auth
    username: admin
    password: admin
    context-redirect: true
```
Did I miss something?
